# CI jobs for g13 driver
stages:
  - code
  - build
flake8:
  stage: code
  allow_failure: true
  needs: []
  before_script:
    - apt update -qq
    - apt install -y python3 python3-pip -qq
    - pip3 install flake8
  script:
    - flake8 *.py
py_compile:
  stage: code
  needs: []
  before_script:
    - apt update -qq
    - apt install -y python3 -qq
  script:
    - python3 -m py_compile *.py
build:
  stage: build
  needs: []
  before_script:
    - apt-get update -qq
    - DEBIAN_FRONTEND="noninteractive" TZ="Etc/UTC" apt-get -qq -y install tzdata
    - apt-get install -y -qq gcc g++ make libusb-1.0-0-dev libboost-all-dev
  script:
    - make -j 2
